### ISSUE TITLE
Create vanilla PSyKAl version of traadv mini-app

### ISSUE THREAD

**Issue by arporter** [arporter/NEMO-DSL#3]
I think we agreed that Rupert would do this. On the other hand, I can do it if required. Once this is done it will help with extending the GOcean infrastructure to 3D (https://github.com/stfc/dl_esm_inf/issues/1) as I'll have an example to work from.

**Comment by rupertford** [comment]
In the last commit I made a change to the original code as there was a bug in it. Two variables were not declared which meant they were being computed as real*4 rather than real*8. I guess this is not necessarily a big deal but it made it impossible for me to get bit reproducible results between the psykal and original versions using my version of gfortran (I'm not sure why). I've therefore declared them as real*8 and all is well.

**Comment by smocavero** [comment]
The declaration of the two variables has been wrongly deleted during the cleaning of the code. Thanks for the bug fix.

**Comment by rupertford** [comment]
Pull request #5 is now on master. Closing issue
